In [6]:
%matplotlib inline
import numpy
import sympy
import pylab
import  random
#from nubapro import autojit
from timeit import default_timer as timer
sympy.init_printing()

import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.axes3d import Axes3D
from matplotlib import animation
from JSAnimation.IPython_display import display_animation

__Problem 1: Calculate trajectory of electron over 100 time steps__

In [25]:
nt = 100 #number of time steps
ts = 10e-11 #s

v_x = 10.0e5 #m/s
v_y = 2.0e5 #m/s
v_z = 1.5e5 #m/s

E_x = 1000. #V/m
E_y = 0
E_z = 0

B = 0.1 #T
e = 1.609e-19 #C
m_e = 9.1094e-31 #kg

In [26]:
#initialize matrix
A = numpy.array([[E_x, E_y, E_z],[v_x, v_y, v_z], [0, 0, B]])
print(A)

[[  1.00000000e+03   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+06   2.00000000e+05   1.50000000e+05]
 [  0.00000000e+00   0.00000000e+00   1.00000000e-01]]


In [27]:
numpy.linalg.det(A)

In [61]:
#time steps
n = numpy.linspace(0, ts*nt, 100)
#print(n)

lastnum = n[-1]
print(lastnum)

1e-08


In [64]:
for locationsX in n:
    
    StepX = n/(E_x + ((v_y**n + v_y**(n+1))/2)*B*e/m_e)

StepX_last = lastnum/(E_x + ((v_y**lastnum + v_y**(lastnum+1))/2)*B*e/m_e)

print('X-location:')
print(StepX_last)

##########

for locationsY in n:
    
    StepY = n/(E_y + ((v_x**n + v_x**(n+1))/2)*B*e/m_e)

StepY_last = lastnum/(E_y - ((v_x**lastnum + v_x**(lastnum+1))/2)*B*e/m_e)

print()
print('Y-location:')
print(StepY_last)

##########

for locationsZ in n:
    
    StepZ = n/(E_z + ((v_y**n + v_y**(n+1))/2)*B*e/m_e)

StepZ_last = lastnum/(E_z - ((v_y**lastnum + v_y**(lastnum+1))/2)*B*e/m_e)

print()
print('Z-location:')
print(StepZ_last)

X-location:
5.66149990138e-24

Y-location:
-1.13230449125e-24

Z-location:
-5.66149990139e-24


__Problem 2: Calculate Trajectory of ion over 100 time steps__

In [65]:
nt = 100 #number of time steps
ts = 10e-5 #s

v_x = 1000. #m/s
v_y = 1000. #m/s
v_z = 1000. #m/s

E_x = 1000. #V/m
E_y = 0
E_z = 0

B = 0.1 #T
e = 1.609e-19 #C
m_ion = 1.6605e-27 #kg (He)

In [66]:
A = numpy.array([[E_x, E_y, E_z],[v_x, v_y, v_z], [0, 0, B]])
print(A)

[[  1.00000000e+03   0.00000000e+00   0.00000000e+00]
 [  1.00000000e+03   1.00000000e+03   1.00000000e+03]
 [  0.00000000e+00   0.00000000e+00   1.00000000e-01]]


In [67]:
numpy.linalg.det(A)

In [68]:
#time steps
n = numpy.linspace(0, ts*nt, 100)
#print(n)

lastnum = n[-1]
print(lastnum)

0.01


In [73]:
for locationsX in n:
    
    StepX = n/(E_x + ((v_y**n + v_y**(n+1))/2)*B*e/m_e)

StepX_last = lastnum/(E_x + ((v_y**lastnum + v_y**(lastnum+1))/2)*B*e/m_e)

print('X-location:')
print(StepX_last)

##########

for locationsY in n:
    
    StepY = n/(E_y + ((v_x**n + v_x**(n+1))/2)*B*e/m_e)

StepY_last = lastnum/(E_y - ((v_x**lastnum + v_x**(lastnum+1))/2)*B*e/m_e)

print()
print('Y-location:')
print(StepY_last)

##########

for locationsZ in n:
    
    StepZ = n/(E_z + ((v_y**n + v_y**(n+1))/2)*B*e/m_e)

StepZ_last = lastnum/(E_z - ((v_y**lastnum + v_y**(lastnum+1))/2)*B*e/m_e)

print()
print('Z-location:')
print(StepZ_last)
print()

X-location:
1.05567356531e-15

Y-location:
-1.05567356543e-15

Z-location:
-1.05567356543e-15



__Problem 3: Visualize trajectories of 10 electrons and 10 ions in x, y, z. Use random number generator for initial velocities of particles__

In [77]:
nt = 100 #number of time steps
ts = 10e-5 #s

v_x = random.randrange(1e5,5e5)*random.choice([-1,1]) #m/s
v_y = random.randrange(1e5,5e5)*random.choice([-1,1]) #m/s
v_z = random.randrange(1e5,5e5)*random.choice([-1,1]) #m/s

E_x = 1000. #V/m
E_y = 0
E_z = 0

B = 0.1 #T
e = 1.609e-19 #C
m_ion = 1.6605e-27 #kg (He)

In [78]:
A = numpy.array([[E_x, E_y, E_z],[v_x, v_y, v_z], [0, 0, B]])
print(A)

[[  1.00000000e+03   0.00000000e+00   0.00000000e+00]
 [  4.45758000e+05   4.71675000e+05  -3.94749000e+05]
 [  0.00000000e+00   0.00000000e+00   1.00000000e-01]]


In [79]:
numpy.linalg.det(A)